### ISSUE TITLE
nr3d_lib 安装不上

### ISSUE THREAD

**Issue by Francisco-liu** [zyqz97/Aerial_lifting#1]
你好，可以给配置好的docker环境吗？
在安装 nr3d_lib 时，报错：
![image](https://github.com/zyqz97/Aerial_lifting/assets/86095216/59962fa0-639e-414d-b929-cd17ec9141f6)

**Comment by zyqz97** [comment]
你好，我是直接用anaconda环境，按照这上面的流程操作 https://github.com/PJLab-ADG/neuralsim?tab=readme-ov-file#installation

**Comment by zyqz97** [comment]
issue #3 mentioned a bug about installing nr3d_lib, maybe you can try it. 
In addition, I suggest installing nr3d_lib from the official repo, rather than this repo.

**Comment by Francisco-liu** [comment]
非常感谢你的回复
