### ISSUE TITLE
processed data lack of coordinates coordinates.pt

### ISSUE THREAD

**Issue by fricenlina** [zyqz97/Aerial_lifting#2]
I download the Yingrenshi's processed data and find it lack of coordinates.pt and mappings.txt. So geometry field could not trianed.
Could you please add them?

**Comment by zyqz97** [comment]
Thanks for pointing out. I will check it later.

**Comment by zyqz97** [comment]
I checked the processed data and found that it has the 'coordinates.pt and mappings.txt'.
