### ISSUE TITLE
Command-line error: invalid error number in diagnostic control option: 20012

### ISSUE THREAD

**Issue by LinLin1031** [zyqz97/Aerial_lifting#3]
During the installation of nr3d_lib using `pip install -v .`, I found a bug:
https://github.com/zyqz97/Aerial_lifting/blob/f771f831f3e4531c11edbca92d7dab4a9656b150/nr3d_lib/setup.py#L370

This bug caused the following error:
![image](https://github.com/zyqz97/Aerial_lifting/assets/50825626/4573d2ee-b3a1-46bf-8f76-72d05dd1819f)
![image](https://github.com/zyqz97/Aerial_lifting/assets/50825626/071a3bdd-3fed-4b9c-bcfd-ee6cf2e38a58)
And that's the mistake: `ERROR: Could not build wheels for nr3d-lib, which is required to install pyproject.toml-based projects`

Compare this line in the source code:
https://github.com/PJLab-ADG/nr3d_lib/blob/1ba93ac63b00810ea4f713280aeb2baf21cbfb4c/setup.py#L663
![image](https://github.com/zyqz97/Aerial_lifting/assets/50825626/91388478-8ec4-458d-b4c8-df863d7cc049)

As you can see, this line should be commented out. After I did this, the error was resolved without any problems. For your reference.
![image](https://github.com/zyqz97/Aerial_lifting/assets/50825626/cd2e2060-f6e2-4459-9b24-6ba75fee7f3b)

**Comment by zyqz97** [comment]
Thanks for your detailed description.
