### ISSUE TITLE
how to visualize your nerf output?

### ISSUE THREAD

**Issue by fricenlina** [zyqz97/Aerial_lifting#5]
Excuse me, how can I visualize the final result? Mega-NeRF Dynamic Viewer or?
不好意思，最后生成的辐射场结果我可以怎么可视化呢？使用Mega-NeRF Dynamic Viewer或者其它工具？

**Comment by fricenlina** [comment]
如果我想获得像是视频里那样的效果呢？

**Comment by zyqz97** [comment]
The demo video is rendered by customizing the fly-through trajectory. Sorry, we did not provide the visualization tools.

**Comment by fricenlina** [comment]
如果我想可视化结果，您能给予任何方法上的指教或提示吗？
If I want to visualize the results, can you give me any suggestions or tips on how to do it?

**Comment by fricenlina** [comment]
我在您之前工作的Issues中看到了类似的提问：https://github.com/zyqz97/GP-NeRF/issues/12#issuecomment-1987164091
我能否理解为，如果我想获得一段连续的输出，可以通过输入一段飞行轨道上的位姿，使用eval代码获得渲染的图片？

**Comment by zyqz97** [comment]
That's right. The core idea is to render the images with the given poses.
