### ISSUE TITLE
Could your method be applied to textured meshes?

### ISSUE THREAD

**Issue by ziwenjie** [zyqz97/Aerial_lifting#7]
Dear Author,

Your work is outstanding. UrbanBIS is a multimodal dataset that also includes textured meshes. Could your method be applied to textured meshes as well? Thank you.

Best regards,

**Comment by zyqz97** [comment]
Hi, thanks for your interest in this work. This NeRF-based method cannot be applied to textured meshes directly. It supports point queries and returns the segmentation results. Maybe you can try.
